"""empty message

Revision ID: 09dee61968b3
Revises: b7776b504018
Create Date: 2019-08-21 14:16:18.146340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09dee61968b3'
down_revision = 'b7776b504018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('room', sa.Integer(), nullable=False),
    sa.Column('from_user', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_room',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('room', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_room')
    op.drop_table('messages')
    op.drop_table('rooms')
    # ### end Alembic commands ###
